const DATA = [
    {
    id: 1,
    date: 'HOJE, 23 DE JANEIRO',
    status: 'BEM',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 2,
    date: 'ONTEM, 22 DE JANEIRO',
    status: 'TRISTE',
    hour: '08:35',
    icon1: 'self_improvement',
    icon2: 'shopping_bag',
    icon3: 'sports_esports',
    actions_safe1: 'Descansei',
    actions_safe2: 'Shopping',
    actions_safe3: 'Jogos',
    actions: ['rest', 'shopp', 'games'],
    descript: 'Hoje foi um dia triste. Meu videogame quebrou, e fui obrigado a ir ao shopping',
    image: require('../assets/humores/happy.png'),
},
{
    id: 3,
    date: 'ANTEONTEM, 21 DE JANEIRO',
    status: 'FELIZ',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 4,
    date: '20 DE JANEIRO',
    status: 'MAL',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 5,
    date: '19 DE JANEIRO',
    status: 'OK',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 6,
    date: '18 DE JANEIRO',
    status: 'INDIFERENTE',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 7,
    date: '17 DE JANEIRO',
    status: 'BEM',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 8,
    date: '16 DE JANEIRO',
    status: 'BEM',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 9,
    date: '15 DE JANEIRO',
    status: 'BEM',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
{
    id: 10,
    date: '14 DE JANEIRO',
    status: 'BEM',
    hour: '08:35',
    icon1: 'celebration',
    icon2: 'sports_soccer',
    icon3: 'restaurant',
    actions_safe1: 'Festa',
    actions_safe2: 'Esport',
    actions_safe3: 'Cozinhar',
    actions: ['party', 'sport', 'cook'],
    descript: 'Hoje foi um dia muito bom. Joguei futebol no parque, cozinhei uma lasanha para minha família. E à noite, fui à festa de aniversário do meu amigo.',
    image: require('../assets/humores/happy.png'),
},
]

export default DATA